version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci(actions)"
    labels:
      - "dependabot"

  - package-ecosystem: "terraform"
    directory: "/github"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci(terraform)"
    labels:
      - "dependabot"
