name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  opentofu-ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: kislerdm/setup-opentofu@main
        with:
          cli_config_credentials_token: ${{ secrets.APP_TERRAFORM_IO_TOKEN }}
          tofu_version: 1.6.0-alpha1

      - name: Format
        run: tofu fmt -recursive

      - name: Init and Lock
        run: |
          MODULES=("github")
          for MODULE in "${MODULES[@]}"; do
            cd "$MODULE"
            tofu init
            tofu providers lock \
              -platform=linux_arm64 \
              -platform=linux_amd64 \
              -platform=darwin_arm64 \
              -platform=darwin_amd64
            cd ..
          done

      - name: Commit and Push
        run: |
          git config user.name "actions-python-ci[bot]"
          git config user.email "147721807+actions-python-ci[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add --all
            git commit -m "ci(terraform): Update terraform code"
            git push origin HEAD:${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          fi
