name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  opentofu-tflint:
    name: TFLint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace: ["github", "terraform-cloud"]

    steps:
      - uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1.0.0
        with:
          tofu_version: 1.6.0-alpha2
          tofu_wrapper: "false"

      - name: Init
        run: tofu init -backend=false
        working-directory: ${{ matrix.workspace }}

      - uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.48.0

      - name: Init tflint
        run: tflint --init
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run tflint
        run: tflint --config=$PWD/../.tflint.hcl --format compact --recursive
        working-directory: ${{ matrix.workspace }}

  opentofu-trivy:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "."
          format: "table"
          exit-code: "1"
